server:
  port: 8200
spring:
  application:
    name: new-movie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  #Eureka Server 相互注册时 hostname 使用 IP 地址
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
hystrix:
  metrics:
    enabled: true
#在feign中使用断路器的开关
feign:
  hystrix:
    enabled: true
