spring:
  application:
    name: newEureka
---
spring:
  #指定profiles为peer1
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    #设置主机名+端口访问实力
    hostname: peer1
  client:
    #Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为。
    #此处若是不禁用，把两个eureka都启动就不会报错了
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #将自己注册到peer2这个eureka上面
      defaultZone: http://localhost:8761/eureka/  #指定eureka服务器的地址
  server:
    #关闭自我保护,如果没有关闭自我保护则会导致客户端继续访问已停微服务
    #开启自我保护后，如果注册表里的服务关闭了，Eureka Server不会注销该服务，会等待服务自动修复
    #为了让其有精准的 CP健康检查，可以关闭自我保护功能，让其剔除不健康节点。
    enable-self-preservation: false
    #定时清理服务器
    eviction-interval-timer-in-ms: 5000


