#spring:
#  application:
#    name: newEureka
#---
#spring:
#  #指定profiles为peer1
#  profiles: peer1
#server:
#  port: 8761
#eureka:
#  instance:
#    #设置主机名+端口访问实力
#    hostname: peer1
#  client:
#    #Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为。
#    #此处若是不禁用，把两个eureka都启动就不会报错了
#    #register-with-eureka: false
#    #fetch-registry: false
#    service-url:
#      #将自己注册到peer2这个eureka上面
#      defaultZone: http://peer2:8762/eureka/  #指定eureka服务器的地址

#同上
#spring:
#  profiles: peer2
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://peer2:8761/eureka/



