server:
  port: 8200
spring:
  application:
    name: new_movie


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #指定服务注册中心地址

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
