server:
  port: 8200
spring:
  application:
    name: new-movie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  #Eureka Server 相互注册时 hostname 使用 IP 地址
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
#设置延迟
hystrix:
  metrics:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000

#feign开启hystrix服务
feign:
  hystrix:
    enabled: true #启用hystrix
    command:
      default:
        execution:
          isolation:
            strategy: #默认是THREAD,这里演示改成了信号量隔离模式
              semaphore:
                maxConcurrentRequests: 3
            thread:
              timeoutInMilliseconds: 5000
          timeout:
            enabled: false


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

